### PR TITLE
remove appcast.xml

### PR DESCRIPTION
**Pull request by claytonrcarter**
If https://github.com/gitx/gitx/pull/285 is successful (big if!) then we can remove the appcast.xml stuff from this site/repo.

### CODE REVIEW

**Comment by hannesa2** [comment]
> If [gitx/gitx#285](https://github.com/gitx/gitx/pull/285) is successful (big if!) then we can remove the appcast.xml stuff from this site/repo.

Is it successful and we can merge this ?

**Comment by claytonrcarter** [comment]
> Is it successful and we can merge this ?

Yes, this can be merged now. Thank you.

**Comment by hannesa2** [comment]
> > Is it successful and we can merge this ?
> 
> Yes, this can be merged now. Thank you.

Really ? In my opinion, it doesn't work properly https://github.com/gitx/gitx/issues/279#issuecomment-1042608304
Or does it work only with next version ?

**Comment by claytonrcarter** [comment]
Well, no, that's not working, but this PR just removes the file `gitx.github.io/appcast.xml`, which is unused. The other work has proved that the correct file best managed in the `gitx/gitx` repo, and that this file is not needed.

**Review by hannesa2 — APPROVED** [review]

**Pull request merged**
